# Generated by Django 4.2.26 on 2025-11-25 05:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projectApp", "0004_doctor_appointment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="specialization",
            new_name="specialty",
        ),
    ]
